
services:
  db-forum:
    image: mysql:8.0
    container_name: db-forum
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: db_forum
      MYSQL_USER: data_admin
      MYSQL_PASSWORD: data_admin
    ports:
      - "3307:3306"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: api-forum
    ports:
      - "8080:8000"
    depends_on:
      - db-forum
    environment:
      DB_HOST: db-forum
      DB_PORT: 3306
      DB_NAME: db_forum
      DB_USER: data_admin
      DB_PASSWORD: data_admin